# Generated by Django 5.2.7 on 2025-11-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0006_remove_media_source_media_src_url_delete_mediasource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="src_url",
            field=models.URLField(max_length=255),
        ),
    ]
