# Generated by Django 6.0.5 on 2026-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0012_alter_collection_desc_alter_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deleted',
            field=models.BooleanField(blank=True, db_comment='If a tag has been soft deleted', default=False),
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', '-post_count'], 'permissions': [('view_deleted_tags', 'Can view deleted tags'), ('restore_deleted_tags', 'Can restore deleted tags')], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
